import type { QuestionCategory } from "@/generated/client";
import type { NamasteCourseId } from "@/lib/courses/namaste-courses";

export type BankQuestion = {
  courseId: NamasteCourseId;
  content: string;
  category: QuestionCategory;
  difficulty?: 1 | 2 | 3;
  topicTags?: string[];
};

export const QUESTION_BANK: BankQuestion[] = [
  // ── Namaste DSA (18) ──────────────────────────────────────────────
  {
    courseId: "namaste-dsa",
    content: "How would you approach finding the longest substring without repeating characters?",
    category: "technical",
    difficulty: 2,
    topicTags: ["strings", "sliding window", "hashing"],
  },
  {
    courseId: "namaste-dsa",
    content: "Explain the difference between BFS and DFS — when would you pick each for a graph problem?",
    category: "technical",
    difficulty: 1,
    topicTags: ["graphs", "BFS", "DFS"],
  },
  {
    courseId: "namaste-dsa",
    content: "Walk me through how you would detect a cycle in a directed graph.",
    category: "technical",
    difficulty: 2,
    topicTags: ["graphs", "cycle detection"],
  },
  {
    courseId: "namaste-dsa",
    content: "How do you solve the two-sum problem efficiently, and what tradeoffs exist between hashing and sorting?",
    category: "technical",
    difficulty: 1,
    topicTags: ["arrays", "hashing"],
  },
  {
    courseId: "namaste-dsa",
    content: "Describe how a min-heap helps with finding the K largest elements in a stream.",
    category: "technical",
    difficulty: 2,
    topicTags: ["heaps", "arrays"],
  },
  {
    courseId: "namaste-dsa",
    content: "How would you validate whether a binary tree is a valid BST?",
    category: "technical",
    difficulty: 2,
    topicTags: ["trees", "BST"],
  },
  {
    courseId: "namaste-dsa",
    content: "Explain memoization versus tabulation in dynamic programming with a concrete example.",
    category: "technical",
    difficulty: 2,
    topicTags: ["DP", "recursion"],
  },
  {
    courseId: "namaste-dsa",
    content: "How would you count the number of islands in a 2D grid?",
    category: "technical",
    difficulty: 2,
    topicTags: ["graphs", "DFS", "matrices"],
  },
  {
    courseId: "namaste-dsa",
    content: "What is the time and space complexity of merge sort, and why is it stable?",
    category: "technical",
    difficulty: 1,
    topicTags: ["sorting", "complexity analysis"],
  },
  {
    courseId: "namaste-dsa",
    content: "How do you find the longest increasing subsequence — what approaches exist?",
    category: "technical",
    difficulty: 3,
    topicTags: ["DP", "arrays"],
  },
  {
    courseId: "namaste-dsa",
    content: "Explain how a trie helps with prefix search and autocomplete.",
    category: "technical",
    difficulty: 2,
    topicTags: ["tries", "strings"],
  },
  {
    courseId: "namaste-dsa",
    content: "How would you design an LRU cache using a hash map and doubly linked list?",
    category: "system_design",
    difficulty: 3,
    topicTags: ["hashing", "design"],
  },
  {
    courseId: "namaste-dsa",
    content: "Describe how union-find (disjoint set) works and a problem where it shines.",
    category: "technical",
    difficulty: 2,
    topicTags: ["graphs", "union-find"],
  },
  {
    courseId: "namaste-dsa",
    content: "How do you reverse a linked list iteratively and recursively?",
    category: "technical",
    difficulty: 1,
    topicTags: ["linked lists", "recursion"],
  },
  {
    courseId: "namaste-dsa",
    content: "What is the sliding window technique — give an example where it beats brute force.",
    category: "technical",
    difficulty: 2,
    topicTags: ["sliding window", "arrays"],
  },
  {
    courseId: "namaste-dsa",
    content: "How would you find the shortest path in an unweighted graph?",
    category: "technical",
    difficulty: 1,
    topicTags: ["graphs", "BFS"],
  },
  {
    courseId: "namaste-dsa",
    content: "Explain topological sort and when you need it in dependency problems.",
    category: "technical",
    difficulty: 2,
    topicTags: ["graphs", "topological sort"],
  },
  {
    courseId: "namaste-dsa",
    content: "How do you approach bit-manipulation problems like counting set bits or finding a single number?",
    category: "technical",
    difficulty: 2,
    topicTags: ["bit manipulation"],
  },

  // ── Namaste React (15) ────────────────────────────────────────────
  {
    courseId: "namaste-react",
    content: "Explain when you would lift state up versus use context in a React app.",
    category: "technical",
    difficulty: 1,
    topicTags: ["state", "context", "patterns"],
  },
  {
    courseId: "namaste-react",
    content: "How does React reconciliation decide what to re-render when props change?",
    category: "technical",
    difficulty: 2,
    topicTags: ["reconciliation", "rendering"],
  },
  {
    courseId: "namaste-react",
    content: "When would you use useMemo versus useCallback, and what mistakes do candidates make?",
    category: "technical",
    difficulty: 2,
    topicTags: ["hooks", "performance"],
  },
  {
    courseId: "namaste-react",
    content: "How do you prevent unnecessary re-renders in a list with hundreds of items?",
    category: "technical",
    difficulty: 2,
    topicTags: ["performance", "rendering", "memo"],
  },
  {
    courseId: "namaste-react",
    content: "Explain the rules of hooks and why they exist.",
    category: "technical",
    difficulty: 1,
    topicTags: ["hooks"],
  },
  {
    courseId: "namaste-react",
    content: "How would you fetch data in a component — compare useEffect versus a data library pattern?",
    category: "technical",
    difficulty: 2,
    topicTags: ["data fetching", "hooks"],
  },
  {
    courseId: "namaste-react",
    content: "What happens during a React batch update, and how does React 18 change batching?",
    category: "technical",
    difficulty: 2,
    topicTags: ["rendering", "batching"],
  },
  {
    courseId: "namaste-react",
    content: "How do controlled and uncontrolled components differ in forms?",
    category: "technical",
    difficulty: 1,
    topicTags: ["forms", "patterns"],
  },
  {
    courseId: "namaste-react",
    content: "Describe how you would debug a component that re-renders on every keystroke.",
    category: "technical",
    difficulty: 2,
    topicTags: ["debugging", "performance"],
  },
  {
    courseId: "namaste-react",
    content: "When is it appropriate to use useReducer instead of useState?",
    category: "technical",
    difficulty: 2,
    topicTags: ["hooks", "state"],
  },
  {
    courseId: "namaste-react",
    content: "How do error boundaries work and what do they not catch?",
    category: "technical",
    difficulty: 2,
    topicTags: ["error handling", "patterns"],
  },
  {
    courseId: "namaste-react",
    content: "Explain key prop behavior in lists — what breaks when keys are unstable?",
    category: "technical",
    difficulty: 1,
    topicTags: ["rendering", "lists"],
  },
  {
    courseId: "namaste-react",
    content: "How would you implement a custom hook for debounced search input?",
    category: "technical",
    difficulty: 2,
    topicTags: ["hooks", "patterns"],
  },
  {
    courseId: "namaste-react",
    content: "Compare composition versus inheritance for sharing UI behavior in React.",
    category: "technical",
    difficulty: 1,
    topicTags: ["patterns", "composition"],
  },
  {
    courseId: "namaste-react",
    content: "How do Suspense and lazy loading fit into a code-splitting strategy?",
    category: "technical",
    difficulty: 2,
    topicTags: ["performance", "lazy loading"],
  },

  // ── Namaste Node.js (15) ──────────────────────────────────────────
  {
    courseId: "namaste-node",
    content: "How do you design idempotent payment webhooks at scale?",
    category: "system_design",
    difficulty: 3,
    topicTags: ["APIs", "scaling", "auth"],
  },
  {
    courseId: "namaste-node",
    content: "Explain the Node.js event loop — what runs on each phase?",
    category: "technical",
    difficulty: 2,
    topicTags: ["event loop", "async"],
  },
  {
    courseId: "namaste-node",
    content: "How would you structure error handling middleware in Express?",
    category: "technical",
    difficulty: 2,
    topicTags: ["APIs", "error handling"],
  },
  {
    courseId: "namaste-node",
    content: "What strategies do you use to prevent SQL injection and validate API input?",
    category: "technical",
    difficulty: 2,
    topicTags: ["APIs", "auth", "security"],
  },
  {
    courseId: "namaste-node",
    content: "How do streams help with large file uploads in Node?",
    category: "technical",
    difficulty: 2,
    topicTags: ["streams", "async"],
  },
  {
    courseId: "namaste-node",
    content: "Describe how you would implement JWT authentication with refresh tokens.",
    category: "technical",
    difficulty: 2,
    topicTags: ["auth", "APIs"],
  },
  {
    courseId: "namaste-node",
    content: "How do you handle database connection pooling in a serverless Node deployment?",
    category: "system_design",
    difficulty: 3,
    topicTags: ["databases", "scaling"],
  },
  {
    courseId: "namaste-node",
    content: "What is the difference between clustering and worker threads in Node?",
    category: "technical",
    difficulty: 2,
    topicTags: ["scaling", "event loop"],
  },
  {
    courseId: "namaste-node",
    content: "How would you rate-limit a public API endpoint?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["APIs", "scaling"],
  },
  {
    courseId: "namaste-node",
    content: "Explain callback hell and how async/await improves readability.",
    category: "technical",
    difficulty: 1,
    topicTags: ["async"],
  },
  {
    courseId: "namaste-node",
    content: "How do you design a REST API for pagination, filtering, and sorting?",
    category: "technical",
    difficulty: 2,
    topicTags: ["APIs"],
  },
  {
    courseId: "namaste-node",
    content: "What caching layers would you add between an Express app and PostgreSQL?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["caching", "databases"],
  },
  {
    courseId: "namaste-node",
    content: "How do you debug a memory leak in a long-running Node process?",
    category: "technical",
    difficulty: 3,
    topicTags: ["debugging", "scaling"],
  },
  {
    courseId: "namaste-node",
    content: "Describe how you would implement graceful shutdown for in-flight requests.",
    category: "technical",
    difficulty: 2,
    topicTags: ["APIs", "scaling"],
  },
  {
    courseId: "namaste-node",
    content: "How would you validate and sanitize file uploads in a Node API?",
    category: "technical",
    difficulty: 2,
    topicTags: ["APIs", "security"],
  },

  // ── Namaste JavaScript (15) ───────────────────────────────────────
  {
    courseId: "namaste-javascript",
    content: "Walk me through closures and a real bug they helped you fix.",
    category: "technical",
    difficulty: 2,
    topicTags: ["closures", "scope"],
  },
  {
    courseId: "namaste-javascript",
    content: "Explain hoisting for var, let, and const with a tricky output example.",
    category: "technical",
    difficulty: 1,
    topicTags: ["hoisting", "scope"],
  },
  {
    courseId: "namaste-javascript",
    content: "How does the `this` keyword behave in arrow functions versus regular functions?",
    category: "technical",
    difficulty: 2,
    topicTags: ["this", "functions"],
  },
  {
    courseId: "namaste-javascript",
    content: "What is the prototype chain and how does inheritance work in JavaScript?",
    category: "technical",
    difficulty: 2,
    topicTags: ["prototypes"],
  },
  {
    courseId: "namaste-javascript",
    content: "Compare Promise.all, Promise.allSettled, and Promise.race with use cases.",
    category: "technical",
    difficulty: 2,
    topicTags: ["async", "promises"],
  },
  {
    courseId: "namaste-javascript",
    content: "What is the temporal dead zone and why does it matter for let/const?",
    category: "technical",
    difficulty: 2,
    topicTags: ["scope", "hoisting"],
  },
  {
    courseId: "namaste-javascript",
    content: "How do you implement debounce and throttle from scratch?",
    category: "technical",
    difficulty: 2,
    topicTags: ["functions", "patterns"],
  },
  {
    courseId: "namaste-javascript",
    content: "Explain event delegation and when you would use it in the DOM.",
    category: "technical",
    difficulty: 1,
    topicTags: ["DOM", "events"],
  },
  {
    courseId: "namaste-javascript",
    content: "What is a microtask versus a macrotask in the browser event loop?",
    category: "technical",
    difficulty: 2,
    topicTags: ["event loop", "async"],
  },
  {
    courseId: "namaste-javascript",
    content: "How do Map and Set differ from plain objects and arrays?",
    category: "technical",
    difficulty: 1,
    topicTags: ["ES6+", "data structures"],
  },
  {
    courseId: "namaste-javascript",
    content: "Explain currying with a practical example from UI or API code.",
    category: "technical",
    difficulty: 2,
    topicTags: ["functions", "patterns"],
  },
  {
    courseId: "namaste-javascript",
    content: "What is the difference between shallow copy and deep copy for nested objects?",
    category: "technical",
    difficulty: 1,
    topicTags: ["objects", "ES6+"],
  },
  {
    courseId: "namaste-javascript",
    content: "How would you polyfill Array.prototype.map for older environments?",
    category: "technical",
    difficulty: 2,
    topicTags: ["arrays", "functions"],
  },
  {
    courseId: "namaste-javascript",
    content: "Describe how async/await desugars to promises under the hood.",
    category: "technical",
    difficulty: 2,
    topicTags: ["async", "promises"],
  },
  {
    courseId: "namaste-javascript",
    content: "What output would you expect from a classic var-in-loop setTimeout interview question?",
    category: "technical",
    difficulty: 2,
    topicTags: ["closures", "async", "hoisting"],
  },

  // ── Namaste Frontend System Design (15) ───────────────────────────
  {
    courseId: "namaste-frontend-system-design",
    content: "Design the frontend architecture for a collaborative document editor.",
    category: "system_design",
    difficulty: 3,
    topicTags: ["architecture", "real-time UI"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "How would you architect infinite scroll for a feed with millions of items?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["performance", "architecture"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "Compare SSR, CSR, and ISR for an e-commerce product listing page.",
    category: "system_design",
    difficulty: 2,
    topicTags: ["SSR", "rendering"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "How do you design a design system that scales across multiple product teams?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["architecture", "patterns"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "What caching strategy would you use for a dashboard with near-real-time metrics?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["caching", "performance"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "How would you handle optimistic UI updates with rollback on failure?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["state at scale", "patterns"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "Design the frontend for a video streaming app with adaptive bitrate playback UI.",
    category: "system_design",
    difficulty: 3,
    topicTags: ["performance", "architecture"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "How do you approach code splitting and bundle analysis in a large SPA?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["performance", "architecture"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "What is your strategy for internationalization and RTL layout at scale?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["architecture", "accessibility"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "How would you build offline-first support for a note-taking web app?",
    category: "system_design",
    difficulty: 3,
    topicTags: ["caching", "state at scale"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "Describe how you would implement feature flags on the frontend safely.",
    category: "system_design",
    difficulty: 2,
    topicTags: ["architecture", "patterns"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "How do you monitor Core Web Vitals in production and act on regressions?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["performance"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "Design a notification center that handles thousands of events per minute.",
    category: "system_design",
    difficulty: 3,
    topicTags: ["real-time UI", "state at scale"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "How would you structure micro-frontends versus a modular monolith?",
    category: "system_design",
    difficulty: 3,
    topicTags: ["architecture"],
  },
  {
    courseId: "namaste-frontend-system-design",
    content: "What accessibility checklist do you run before shipping a complex form?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["accessibility", "patterns"],
  },

  // ── Crack Frontend Interview (12) ─────────────────────────────────
  {
    courseId: "namaste-interview",
    content: "Tell me about a frontend bug you debugged under time pressure.",
    category: "behavioral",
    difficulty: 2,
    topicTags: ["debugging", "communication"],
  },
  {
    courseId: "namaste-interview",
    content: "How would you center a div — and what follow-up questions might an interviewer ask?",
    category: "technical",
    difficulty: 1,
    topicTags: ["CSS", "DOM"],
  },
  {
    courseId: "namaste-interview",
    content: "Explain event bubbling and capturing with a practical DOM example.",
    category: "technical",
    difficulty: 1,
    topicTags: ["DOM", "events"],
  },
  {
    courseId: "namaste-interview",
    content: "What is the box model and how does box-sizing affect layout?",
    category: "technical",
    difficulty: 1,
    topicTags: ["CSS"],
  },
  {
    courseId: "namaste-interview",
    content: "How do you optimize Largest Contentful Paint on a marketing landing page?",
    category: "technical",
    difficulty: 2,
    topicTags: ["performance"],
  },
  {
    courseId: "namaste-interview",
    content: "Describe a time you had to push back on a unrealistic frontend deadline.",
    category: "behavioral",
    difficulty: 2,
    topicTags: ["communication"],
  },
  {
    courseId: "namaste-interview",
    content: "How would you implement a simple autocomplete search box?",
    category: "technical",
    difficulty: 2,
    topicTags: ["JS", "DOM"],
  },
  {
    courseId: "namaste-interview",
    content: "Compare flexbox and CSS grid — when do you reach for each?",
    category: "technical",
    difficulty: 1,
    topicTags: ["CSS"],
  },
  {
    courseId: "namaste-interview",
    content: "What is CORS and how have you handled it in frontend-backend integration?",
    category: "technical",
    difficulty: 2,
    topicTags: ["APIs", "security"],
  },
  {
    courseId: "namaste-interview",
    content: "Walk me through how you would test a React component that fetches data.",
    category: "technical",
    difficulty: 2,
    topicTags: ["React", "testing"],
  },
  {
    courseId: "namaste-interview",
    content: "Tell me about a frontend performance win you shipped and how you measured it.",
    category: "behavioral",
    difficulty: 2,
    topicTags: ["performance", "communication"],
  },
  {
    courseId: "namaste-interview",
    content: "How do you stay current with frontend interview topics while job hunting?",
    category: "behavioral",
    difficulty: 1,
    topicTags: ["communication"],
  },

  // ── MERN Stack Bundle (12) ────────────────────────────────────────
  {
    courseId: "mern-stack-bundle",
    content: "Design a full-stack feature: user posts a comment and sees it instantly without refresh.",
    category: "system_design",
    difficulty: 2,
    topicTags: ["React", "Node", "full-stack"],
  },
  {
    courseId: "mern-stack-bundle",
    content: "How would you model users, posts, and comments in MongoDB versus a relational schema?",
    category: "technical",
    difficulty: 2,
    topicTags: ["MongoDB", "data modeling"],
  },
  {
    courseId: "mern-stack-bundle",
    content: "Explain JWT flow end-to-end from React login form to protected Express route.",
    category: "technical",
    difficulty: 2,
    topicTags: ["auth", "React", "Node"],
  },
  {
    courseId: "mern-stack-bundle",
    content: "How do you handle optimistic UI for a like button backed by a REST API?",
    category: "technical",
    difficulty: 2,
    topicTags: ["React", "APIs", "state"],
  },
  {
    courseId: "mern-stack-bundle",
    content: "What indexing strategy would you use for a MongoDB feed sorted by createdAt?",
    category: "technical",
    difficulty: 2,
    topicTags: ["MongoDB", "scaling"],
  },
  {
    courseId: "mern-stack-bundle",
    content: "How would you structure a monorepo with shared types between React and Express?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["architecture", "full-stack"],
  },
  {
    courseId: "mern-stack-bundle",
    content: "Describe error boundaries on the client plus centralized error middleware on the server.",
    category: "technical",
    difficulty: 2,
    topicTags: ["React", "Node", "error handling"],
  },
  {
    courseId: "mern-stack-bundle",
    content: "How do you prevent NoSQL injection in an Express + MongoDB app?",
    category: "technical",
    difficulty: 2,
    topicTags: ["MongoDB", "security"],
  },
  {
    courseId: "mern-stack-bundle",
    content: "Design pagination for an infinite-scroll MERN feed with cursor-based API.",
    category: "system_design",
    difficulty: 2,
    topicTags: ["APIs", "React", "MongoDB"],
  },
  {
    courseId: "mern-stack-bundle",
    content: "How would you deploy a MERN app with separate frontend and API on Vercel/Railway?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["deployment", "full-stack"],
  },
  {
    courseId: "mern-stack-bundle",
    content: "Explain how you would add real-time notifications using WebSockets in a MERN stack.",
    category: "system_design",
    difficulty: 3,
    topicTags: ["real-time", "Node", "React"],
  },
  {
    courseId: "mern-stack-bundle",
    content: "How do you validate request bodies with Zod on Express and share schemas with React forms?",
    category: "technical",
    difficulty: 2,
    topicTags: ["APIs", "React", "validation"],
  },

  // ── Frontend Master Bundle (12) ───────────────────────────────────
  {
    courseId: "frontend-master-bundle",
    content: "Design a React dashboard that loads under 2s on 3G — what would you prioritize?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["React", "performance", "FSD"],
  },
  {
    courseId: "frontend-master-bundle",
    content: "How would you architect global state for a multi-tab analytics product?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["React", "state at scale"],
  },
  {
    courseId: "frontend-master-bundle",
    content: "Compare React Server Components with client-side data fetching for a product page.",
    category: "system_design",
    difficulty: 2,
    topicTags: ["SSR", "React", "FSD"],
  },
  {
    courseId: "frontend-master-bundle",
    content: "How do you design a component library API that stays stable across major versions?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["architecture", "React"],
  },
  {
    courseId: "frontend-master-bundle",
    content: "What rendering strategy would you pick for a SEO-critical blog inside a React app?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["SSR", "rendering"],
  },
  {
    courseId: "frontend-master-bundle",
    content: "How would you implement virtualized tables with sorting and filtering?",
    category: "technical",
    difficulty: 3,
    topicTags: ["React", "performance"],
  },
  {
    courseId: "frontend-master-bundle",
    content: "Design frontend observability: what client-side metrics and errors do you capture?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["FSD", "monitoring"],
  },
  {
    courseId: "frontend-master-bundle",
    content: "How do you manage authentication state across SSR and client hydration?",
    category: "system_design",
    difficulty: 3,
    topicTags: ["SSR", "auth", "React"],
  },
  {
    courseId: "frontend-master-bundle",
    content: "Explain how you would split a large React app by route and by feature team ownership.",
    category: "system_design",
    difficulty: 2,
    topicTags: ["architecture", "React"],
  },
  {
    courseId: "frontend-master-bundle",
    content: "What tradeoffs exist between CSS modules, Tailwind, and CSS-in-JS at scale?",
    category: "technical",
    difficulty: 2,
    topicTags: ["CSS", "architecture"],
  },
  {
    courseId: "frontend-master-bundle",
    content: "How would you build a theming system supporting light, dark, and high-contrast modes?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["patterns", "accessibility"],
  },
  {
    courseId: "frontend-master-bundle",
    content: "Design a file upload flow with progress, retry, and client-side validation.",
    category: "system_design",
    difficulty: 2,
    topicTags: ["React", "APIs", "UX"],
  },

  // ── Advanced FullStack Bundle (12) ────────────────────────────────
  {
    courseId: "advanced-fullstack-bundle",
    content: "Design a multi-tenant SaaS dashboard spanning React UI, Node APIs, and role-based access.",
    category: "system_design",
    difficulty: 3,
    topicTags: ["full-stack", "auth", "architecture"],
  },
  {
    courseId: "advanced-fullstack-bundle",
    content: "How would you implement end-to-end tracing from a React click to a database query?",
    category: "system_design",
    difficulty: 3,
    topicTags: ["monitoring", "full-stack"],
  },
  {
    courseId: "advanced-fullstack-bundle",
    content: "Compare monolith, modular monolith, and microservices for a Series A startup.",
    category: "system_design",
    difficulty: 2,
    topicTags: ["architecture"],
  },
  {
    courseId: "advanced-fullstack-bundle",
    content: "How do you design API versioning when mobile and web clients ship on different cadences?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["APIs", "Node"],
  },
  {
    courseId: "advanced-fullstack-bundle",
    content: "Describe a caching strategy from CDN edge through API to database read replicas.",
    category: "system_design",
    difficulty: 3,
    topicTags: ["caching", "scaling"],
  },
  {
    courseId: "advanced-fullstack-bundle",
    content: "How would you build a collaborative whiteboard with React canvas and Node sync?",
    category: "system_design",
    difficulty: 3,
    topicTags: ["real-time UI", "React", "Node"],
  },
  {
    courseId: "advanced-fullstack-bundle",
    content: "What is your approach to schema migrations without downtime in production?",
    category: "system_design",
    difficulty: 3,
    topicTags: ["databases", "Node"],
  },
  {
    courseId: "advanced-fullstack-bundle",
    content: "How do you secure a full-stack app against CSRF, XSS, and SSRF?",
    category: "technical",
    difficulty: 2,
    topicTags: ["security", "full-stack"],
  },
  {
    courseId: "advanced-fullstack-bundle",
    content: "Design a background job system for sending emails and processing uploads.",
    category: "system_design",
    difficulty: 2,
    topicTags: ["Node", "scaling"],
  },
  {
    courseId: "advanced-fullstack-bundle",
    content: "How would you load-test an Express API and interpret the results for frontend SLAs?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["scaling", "APIs"],
  },
  {
    courseId: "advanced-fullstack-bundle",
    content: "Explain how you would implement feature flags across React and Node with consistent behavior.",
    category: "system_design",
    difficulty: 2,
    topicTags: ["architecture", "full-stack"],
  },
  {
    courseId: "advanced-fullstack-bundle",
    content: "How do you decide what logic lives in the frontend versus the backend for a complex form wizard?",
    category: "system_design",
    difficulty: 2,
    topicTags: ["architecture", "React", "Node"],
  },

  // ── Job Custom (8) ────────────────────────────────────────────────
  {
    courseId: "job-custom",
    content: "Tell me about a project that best matches this role's requirements.",
    category: "behavioral",
    difficulty: 1,
    topicTags: ["role-fit"],
  },
  {
    courseId: "job-custom",
    content: "Walk me through a technical decision you made that had significant tradeoffs.",
    category: "behavioral",
    difficulty: 2,
    topicTags: ["communication"],
  },
  {
    courseId: "job-custom",
    content: "Describe a time you had to learn a new technology quickly to deliver on a deadline.",
    category: "behavioral",
    difficulty: 2,
    topicTags: ["learning"],
  },
  {
    courseId: "job-custom",
    content: "How do your recent projects align with the responsibilities in this job description?",
    category: "behavioral",
    difficulty: 1,
    topicTags: ["role-fit"],
  },
  {
    courseId: "job-custom",
    content: "Tell me about a production incident you handled and what you changed afterward.",
    category: "behavioral",
    difficulty: 2,
    topicTags: ["incident response"],
  },
  {
    courseId: "job-custom",
    content: "What would you prioritize in your first 30 days if you joined this team?",
    category: "behavioral",
    difficulty: 1,
    topicTags: ["role-fit"],
  },
  {
    courseId: "job-custom",
    content: "Describe a cross-functional collaboration that improved delivery quality.",
    category: "behavioral",
    difficulty: 2,
    topicTags: ["communication"],
  },
  {
    courseId: "job-custom",
    content: "What gaps do you see between your current skills and this role, and how are you closing them?",
    category: "behavioral",
    difficulty: 2,
    topicTags: ["role-fit", "learning"],
  },
];

export function getQuestionBankStats() {
  const byCourse = new Map<string, number>();
  for (const question of QUESTION_BANK) {
    byCourse.set(question.courseId, (byCourse.get(question.courseId) ?? 0) + 1);
  }
  return {
    total: QUESTION_BANK.length,
    byCourse: Object.fromEntries(byCourse),
  };
}
